### ISSUE TITLE
MissingPluginException(No implementation found for method loadWifiList on channel wifi_iot)

### ISSUE THREAD

**Issue by VimeshPolaris** [flutternetwork/WiFiFlutter#249]
Hello their,
I'm trying to implement this package in Futter iOS.
In Android, it works completely but in iOS it's not working.
**Can anyone help with this?**

```
flutter: MissingPluginException : MissingPluginException(No implementation found for method loadWifiList on channel wifi_iot)

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞═════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
plugins.wififlutter.io/wifi_scan:
MissingPluginException(No implementation found for method listen on channel
plugins.wififlutter.io/wifi_scan)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506:9)
<asynchronous suspension>
══════════════════════════════════════════════════════════════════
```

**Comment by daadu** [comment]
It is not supported in iOS.

**Comment by VimeshPolaris** [comment]
Then what can be use for getting nearby all wifi in iOS ?

**Comment by daadu** [comment]
There is no API for it. Check readme of [wifi_scan](https://github.com/flutternetwork/WiFiFlutter/tree/master/packages/wifi_scan).

**Comment by daadu** [comment]
For IoT, on thing that most devices do while provisioning is, after connecting to device's AP, it asks the device to scan and get that results. That way you are not dependent on Mobile platforms to get wifi list.
