### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported value: 'WIFI_AP_STATE_DISABLED' of type 'class info.whitebyte.hotspotmanager.WIFI_AP_STATE'

### ISSUE THREAD

**Issue by Doldrums** [flutternetwork/WiFiFlutter#312]
```
java.lang.IllegalArgumentException: Unsupported value: 'WIFI_AP_STATE_DISABLED' of type 'class info.whitebyte.hotspotmanager.WIFI_AP_STATE'
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:63)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/MethodChannel#wifi_iot(23667): 	at com.alternadom.wifiiot.WifiIotPlugin.getWiFiAPState(WifiIotPlugin.java:675)
E/MethodChannel#wifi_iot(23667): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:309)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#wifi_iot(23667): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#wifi_iot(23667): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#wifi_iot(23667): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#wifi_iot(23667): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#wifi_iot(23667): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#wifi_iot(23667): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#wifi_iot(23667): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#wifi_iot(23667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MethodChannel#wifi_iot(23667): Failed to handle method call
java.lang.IllegalArgumentException: Unsupported value: 'WIFI_AP_STATE_DISABLED' of type 'class info.whitebyte.hotspotmanager.WIFI_AP_STATE'
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:63)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/MethodChannel#wifi_iot(23667): 	at com.alternadom.wifiiot.WifiIotPlugin.getWiFiAPState(WifiIotPlugin.java:675)
E/MethodChannel#wifi_iot(23667): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:309)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#wifi_iot(23667): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#wifi_iot(23667): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#wifi_iot(23667): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#wifi_iot(23667): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#wifi_iot(23667): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#wifi_iot(23667): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#wifi_iot(23667): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#wifi_iot(23667): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#wifi_iot(23667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MethodChannel#wifi_iot(23667): Failed to handle method call

```

**Comment by Doldrums** [comment]
@daadu could u take a look

**Comment by soniarojhwal** [comment]
any update?

**Comment by dzen1984** [comment]
any update?

**Comment by susundberg** [comment]
I also hit the very same issue

**Comment by phdinh94** [comment]
Same issue

**Comment by daadu** [comment]
Guys, this is AP functionality, which is broken from SDK 26 and above. The example app is out of date as long as AP functionality is concerned.

**Comment by susundberg** [comment]
I guess you know the best, to me the error code looked like the platform - communication failed for some mysterious reason; like it would not be able to encode the ENUM value of WIFI_AP_STATE_DISABLED

**Comment by nuxwork** [comment]
Same issue

**Comment by nuxwork** [comment]
original:
```
  private void getWiFiAPState(Result poResult) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
      poResult.success(moWiFiAPManager.getWifiApState().ordinal());
    } else {
      poResult.success(localOnlyHotspotState);
    }
  }
```
fixed:
```
  private void getWiFiAPState(Result poResult) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
      poResult.success(moWiFiAPManager.getWifiApState().ordinal());
    } else {
      poResult.success(localOnlyHotspotState.ordinal());
    }
  }
```

**Comment by integraodessa** [comment]
Android 12 API 35 nothing works
![example](https://github.com/flutternetwork/WiFiFlutter/assets/106528228/52e1003c-231b-4b89-8004-5da9e6af3513)
![image](https://github.com/flutternetwork/WiFiFlutter/assets/106528228/ae594a72-c14d-443d-b012-7874cc83dd12)

**Comment by fabioselau077** [comment]
> Android 12 API 35 nothing works ![example](https://private-user-images.githubusercontent.com/106528228/283124847-52e1003c-231b-4b89-8004-5da9e6af3513.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDk1OTYsIm5iZiI6MTcwNDQwOTI5NiwicGF0aCI6Ii8xMDY1MjgyMjgvMjgzMTI0ODQ3LTUyZTEwMDNjLTIzMWItNGI4OS04MDA0LTVkYTllNmFmMzUxMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQyMzAxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTAxMjY3NjVkMjYzMzM5NTAzMzg2NmI1OWViZWEyMTQwZmUyMTdjMTdiYTBjMzYxMWE2NmU0YzQyN2Q3NmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eDmu3EPjboesxph7I-5RgooESjry1u2LWoeWxr-dhOA)

same here

**Comment by isaaclkh** [comment]
Is there any updates?
